# Generated by Django 2.2.7 on 2020-09-21 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='awscredentials',
            name='default_region',
            field=models.CharField(default='us-east-1', max_length=32),
        ),
    ]
