# Generated by Django 2.2.7 on 2020-09-21 22:22

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_awscredentials_default_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='EC2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(max_length=255)),
                ('instance_type', models.CharField(max_length=255)),
                ('state', models.BooleanField()),
                ('instance_data', jsonfield.fields.JSONField(null=True)),
                ('credentials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AWSCredentials')),
            ],
        ),
    ]
