# Generated by Django 2.2.7 on 2020-09-13 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_casetimeseries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casetimeseries',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
